trigger:
  branches:
    include:
      - main

pool:
  name: "Default"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.0.x"

  - script: |
      dotnet restore StudentApp.sln
    displayName: "Restore dependencies"

  - script: |
      dotnet build StudentApp.sln --configuration Release
    displayName: "Build Solution"

  - script: |
      echo "Iniciando StudentApp en segundo plano..."
      start /B cmd /c "dotnet run --project StudentApp/StudentApp.csproj --no-build > studentapp.log 2>&1"
      echo "Esperando 30 segundos para que la aplicación levante..."
      timeout /t 30 /nobreak
    displayName: "Start StudentApp"

  - script: |
      echo "Verificando si la aplicación está corriendo en el puerto 7047..."
      netstat -ano | findstr :7047
    displayName: "Check if StudentApp is running"

  - script: |
      dotnet test StudentApp.Tests/StudentApp.Tests.csproj --no-restore --verbosity normal
    displayName: "Run Selenium Tests"

  - script: |
      echo "Finalizando procesos de StudentApp..."
      taskkill /F /IM dotnet.exe || echo "No se encontraron procesos activos"
    displayName: "Stop StudentApp"
    condition: always()
