trigger:
  branches:
    include:
      - main

pool:
  name: "Default"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.0.x"

  - script: |
      dotnet restore StudentApp.sln
    displayName: "Restore dependencies"

  - script: |
      dotnet build StudentApp.sln --configuration Release
    displayName: "Build Solution"

  - script: |
      echo "Iniciando StudentApp en segundo plano..."
      start /B cmd /c "dotnet run --project StudentApp/StudentApp.csproj --no-build > studentapp.log 2>&1"
      echo "Esperando 30 segundos para que la aplicación levante..."
      timeout /t 30 /nobreak

      echo "Verificando si StudentApp está corriendo..."
      for /L %%i in (1,1,5) do (
        netstat -ano | findstr :7047 && exit /b 0
        echo "Intento %%i: La aplicación aún no responde, esperando..."
        timeout /t 5 /nobreak
      )
      
      echo "ERROR: StudentApp no levantó correctamente. Revisar studentapp.log"
      type studentapp.log
      exit /b 1
    displayName: "Start StudentApp"

  - script: |
      echo "Verificando que ProfessorAppAPI está corriendo..."
      netstat -ano | findstr :7039 || (
        echo "ERROR: ProfessorAppAPI no está corriendo en el puerto esperado."
        exit /b 1
      )
    displayName: "Check if ProfessorAppAPI is running"

  - script: |
      echo "Ejecutando pruebas Selenium..."
      dotnet test StudentApp.Tests/StudentApp.Tests.csproj --no-restore --verbosity normal
    displayName: "Run Selenium Tests"

  - script: |
      echo "Finalizando procesos de StudentApp..."
      taskkill /F /IM dotnet.exe || echo "No se encontraron procesos activos"
    displayName: "Stop StudentApp"
    condition: always()
