trigger:
  branches:
    include:
      - main

pool:
  name: "Default"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.0.x"

  - script: |
      dotnet restore StudentApp.sln
    displayName: "Restore dependencies"

  - script: |
      dotnet build StudentApp.sln --configuration Release
    displayName: "Build Solution"

  - script: |
      echo "Iniciando StudentApp..."
      dotnet run --project StudentApp/StudentApp.csproj --no-build &
      echo "Esperando 30 segundos para que la aplicación levante..."
      sleep 30

      echo "Verificando si StudentApp está corriendo en el puerto 7047..."
      netstat -ano | grep :7047 || (
        echo "ERROR: StudentApp no levantó correctamente."
        exit 1
      )
    displayName: "Start StudentApp"
